# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Device(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, type: str=None, location: str=None):  # noqa: E501
        """Device - a model defined in Swagger

        :param id: The id of this Device.  # noqa: E501
        :type id: str
        :param type: The type of this Device.  # noqa: E501
        :type type: str
        :param location: The location of this Device.  # noqa: E501
        :type location: str
        """
        self.swagger_types = {
            'id': str,
            'type': str,
            'location': str
        }

        self.attribute_map = {
            'id': 'id',
            'type': 'type',
            'location': 'location'
        }
        self._id = id
        self._type = type
        self._location = location

    @classmethod
    def from_dict(cls, dikt) -> 'Device':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Device of this Device.  # noqa: E501
        :rtype: Device
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Device.


        :return: The id of this Device.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Device.


        :param id: The id of this Device.
        :type id: str
        """

        self._id = id

    @property
    def type(self) -> str:
        """Gets the type of this Device.


        :return: The type of this Device.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Device.


        :param type: The type of this Device.
        :type type: str
        """

        self._type = type

    @property
    def location(self) -> str:
        """Gets the location of this Device.


        :return: The location of this Device.
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location: str):
        """Sets the location of this Device.


        :param location: The location of this Device.
        :type location: str
        """

        self._location = location
