# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.package_package_details import PackagePackageDetails  # noqa: F401,E501
from swagger_server.models.package_sender import PackageSender  # noqa: F401,E501
from swagger_server import util


class Package(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, sender: PackageSender=None, recipient: PackageSender=None, package_details: PackagePackageDetails=None):  # noqa: E501
        """Package - a model defined in Swagger

        :param id: The id of this Package.  # noqa: E501
        :type id: str
        :param sender: The sender of this Package.  # noqa: E501
        :type sender: PackageSender
        :param recipient: The recipient of this Package.  # noqa: E501
        :type recipient: PackageSender
        :param package_details: The package_details of this Package.  # noqa: E501
        :type package_details: PackagePackageDetails
        """
        self.swagger_types = {
            'id': str,
            'sender': PackageSender,
            'recipient': PackageSender,
            'package_details': PackagePackageDetails
        }

        self.attribute_map = {
            'id': 'id',
            'sender': 'sender',
            'recipient': 'recipient',
            'package_details': 'packageDetails'
        }
        self._id = id
        self._sender = sender
        self._recipient = recipient
        self._package_details = package_details

    @classmethod
    def from_dict(cls, dikt) -> 'Package':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Package of this Package.  # noqa: E501
        :rtype: Package
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Package.


        :return: The id of this Package.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Package.


        :param id: The id of this Package.
        :type id: str
        """

        self._id = id

    @property
    def sender(self) -> PackageSender:
        """Gets the sender of this Package.


        :return: The sender of this Package.
        :rtype: PackageSender
        """
        return self._sender

    @sender.setter
    def sender(self, sender: PackageSender):
        """Sets the sender of this Package.


        :param sender: The sender of this Package.
        :type sender: PackageSender
        """

        self._sender = sender

    @property
    def recipient(self) -> PackageSender:
        """Gets the recipient of this Package.


        :return: The recipient of this Package.
        :rtype: PackageSender
        """
        return self._recipient

    @recipient.setter
    def recipient(self, recipient: PackageSender):
        """Sets the recipient of this Package.


        :param recipient: The recipient of this Package.
        :type recipient: PackageSender
        """

        self._recipient = recipient

    @property
    def package_details(self) -> PackagePackageDetails:
        """Gets the package_details of this Package.


        :return: The package_details of this Package.
        :rtype: PackagePackageDetails
        """
        return self._package_details

    @package_details.setter
    def package_details(self, package_details: PackagePackageDetails):
        """Sets the package_details of this Package.


        :param package_details: The package_details of this Package.
        :type package_details: PackagePackageDetails
        """

        self._package_details = package_details
