# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PackageResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, package_id: str=None, status: str=None):  # noqa: E501
        """PackageResponse - a model defined in Swagger

        :param package_id: The package_id of this PackageResponse.  # noqa: E501
        :type package_id: str
        :param status: The status of this PackageResponse.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'package_id': str,
            'status': str
        }

        self.attribute_map = {
            'package_id': 'packageId',
            'status': 'status'
        }
        self._package_id = package_id
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'PackageResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PackageResponse of this PackageResponse.  # noqa: E501
        :rtype: PackageResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def package_id(self) -> str:
        """Gets the package_id of this PackageResponse.


        :return: The package_id of this PackageResponse.
        :rtype: str
        """
        return self._package_id

    @package_id.setter
    def package_id(self, package_id: str):
        """Sets the package_id of this PackageResponse.


        :param package_id: The package_id of this PackageResponse.
        :type package_id: str
        """

        self._package_id = package_id

    @property
    def status(self) -> str:
        """Gets the status of this PackageResponse.


        :return: The status of this PackageResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this PackageResponse.


        :param status: The status of this PackageResponse.
        :type status: str
        """

        self._status = status
