# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PackageSender(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, address: str=None):  # noqa: E501
        """PackageSender - a model defined in Swagger

        :param name: The name of this PackageSender.  # noqa: E501
        :type name: str
        :param address: The address of this PackageSender.  # noqa: E501
        :type address: str
        """
        self.swagger_types = {
            'name': str,
            'address': str
        }

        self.attribute_map = {
            'name': 'name',
            'address': 'address'
        }
        self._name = name
        self._address = address

    @classmethod
    def from_dict(cls, dikt) -> 'PackageSender':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Package_sender of this PackageSender.  # noqa: E501
        :rtype: PackageSender
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this PackageSender.


        :return: The name of this PackageSender.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this PackageSender.


        :param name: The name of this PackageSender.
        :type name: str
        """

        self._name = name

    @property
    def address(self) -> str:
        """Gets the address of this PackageSender.


        :return: The address of this PackageSender.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this PackageSender.


        :param address: The address of this PackageSender.
        :type address: str
        """

        self._address = address
