# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PackagePackageDetails(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, weight: float=None, dimensions: str=None, content: str=None):  # noqa: E501
        """PackagePackageDetails - a model defined in Swagger

        :param weight: The weight of this PackagePackageDetails.  # noqa: E501
        :type weight: float
        :param dimensions: The dimensions of this PackagePackageDetails.  # noqa: E501
        :type dimensions: str
        :param content: The content of this PackagePackageDetails.  # noqa: E501
        :type content: str
        """
        self.swagger_types = {
            'weight': float,
            'dimensions': str,
            'content': str
        }

        self.attribute_map = {
            'weight': 'weight',
            'dimensions': 'dimensions',
            'content': 'content'
        }
        self._weight = weight
        self._dimensions = dimensions
        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'PackagePackageDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Package_packageDetails of this PackagePackageDetails.  # noqa: E501
        :rtype: PackagePackageDetails
        """
        return util.deserialize_model(dikt, cls)

    @property
    def weight(self) -> float:
        """Gets the weight of this PackagePackageDetails.


        :return: The weight of this PackagePackageDetails.
        :rtype: float
        """
        return self._weight

    @weight.setter
    def weight(self, weight: float):
        """Sets the weight of this PackagePackageDetails.


        :param weight: The weight of this PackagePackageDetails.
        :type weight: float
        """

        self._weight = weight

    @property
    def dimensions(self) -> str:
        """Gets the dimensions of this PackagePackageDetails.


        :return: The dimensions of this PackagePackageDetails.
        :rtype: str
        """
        return self._dimensions

    @dimensions.setter
    def dimensions(self, dimensions: str):
        """Sets the dimensions of this PackagePackageDetails.


        :param dimensions: The dimensions of this PackagePackageDetails.
        :type dimensions: str
        """

        self._dimensions = dimensions

    @property
    def content(self) -> str:
        """Gets the content of this PackagePackageDetails.


        :return: The content of this PackagePackageDetails.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content: str):
        """Sets the content of this PackagePackageDetails.


        :param content: The content of this PackagePackageDetails.
        :type content: str
        """

        self._content = content
