# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TrackingInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, tracking_number: str=None, status: str=None, estimated_delivery: date=None):  # noqa: E501
        """TrackingInfo - a model defined in Swagger

        :param tracking_number: The tracking_number of this TrackingInfo.  # noqa: E501
        :type tracking_number: str
        :param status: The status of this TrackingInfo.  # noqa: E501
        :type status: str
        :param estimated_delivery: The estimated_delivery of this TrackingInfo.  # noqa: E501
        :type estimated_delivery: date
        """
        self.swagger_types = {
            'tracking_number': str,
            'status': str,
            'estimated_delivery': date
        }

        self.attribute_map = {
            'tracking_number': 'trackingNumber',
            'status': 'status',
            'estimated_delivery': 'estimatedDelivery'
        }
        self._tracking_number = tracking_number
        self._status = status
        self._estimated_delivery = estimated_delivery

    @classmethod
    def from_dict(cls, dikt) -> 'TrackingInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TrackingInfo of this TrackingInfo.  # noqa: E501
        :rtype: TrackingInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tracking_number(self) -> str:
        """Gets the tracking_number of this TrackingInfo.


        :return: The tracking_number of this TrackingInfo.
        :rtype: str
        """
        return self._tracking_number

    @tracking_number.setter
    def tracking_number(self, tracking_number: str):
        """Sets the tracking_number of this TrackingInfo.


        :param tracking_number: The tracking_number of this TrackingInfo.
        :type tracking_number: str
        """

        self._tracking_number = tracking_number

    @property
    def status(self) -> str:
        """Gets the status of this TrackingInfo.


        :return: The status of this TrackingInfo.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this TrackingInfo.


        :param status: The status of this TrackingInfo.
        :type status: str
        """

        self._status = status

    @property
    def estimated_delivery(self) -> date:
        """Gets the estimated_delivery of this TrackingInfo.


        :return: The estimated_delivery of this TrackingInfo.
        :rtype: date
        """
        return self._estimated_delivery

    @estimated_delivery.setter
    def estimated_delivery(self, estimated_delivery: date):
        """Sets the estimated_delivery of this TrackingInfo.


        :param estimated_delivery: The estimated_delivery of this TrackingInfo.
        :type estimated_delivery: date
        """

        self._estimated_delivery = estimated_delivery
